# Generated by Django 4.0.4 on 2022-05-11 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_alter_photo_tags_video'),
        ('events', '0002_event_video_eventvideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='photos.video'),
        ),
    ]
