# Generated by Django 4.0.4 on 2022-05-17 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_alter_photo_tags_alter_video_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='videos', to='photos.tag'),
        ),
    ]
